module.exports = {
	strings: [
		"hobnob",
		"ben and nicks",
		"pi Bar",
		"toronado",
		"la trappe",
		"mcgees",
		"minibar",
		"trappist",
		"monk’s kettle",
		"public house",
		"beer revolution",
		"bin 55",
		"zeitgeist",
		"cato's ale house",
		"the page",
		"city beer store",
		"mission bowling club",
		"bar crudo",
		"lucky 13",
		"rosamunde",
		"nopa"
	],

	regEx: [
		/hobnob/,
		/ben and nicks/,
		/pi Bar/,
		/toronado/,
		/la trappe/,
		/mcgees/,
		/minibar/,
		/trappist/,
		/monk’s kettle/,
		/public house/,
		/beer revolution/,
		/bin 55/,
		/zeitgeist/,
		/cato's ale house/,
		/the page/,
		/city beer store/,
		/mission bowling club/,
		/bar crudo/,
		/lucky 13/,
		/rosamunde/,
		/nopa/
	]
}